# Generated by Django 5.2.9 on 2025-12-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=50)),
                ('color_theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('guide_type', models.CharField(choices=[('critical', 'Critical'), ('standard', 'Standard')], max_length=20)),
                ('steps_text', models.TextField(help_text='Enter each step on a new line')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('before', 'Before Event'), ('during', 'During Event'), ('after', 'After Event')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='support.disaster')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
