# Generated by Django 5.2.9 on 2025-12-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_type', models.CharField(choices=[('danger', 'Danger Zone'), ('safe', 'Safe Haven')], max_length=10)),
                ('radius', models.FloatField(default=1000, help_text='Radius in meters (for Danger Zones)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
