# Generated by Django 5.2.9 on 2025-12-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
