# Generated by Django 5.2.9 on 2025-12-21 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('Fire', 'Fire & Rescue'), ('Medical', 'Medical'), ('Police', 'Police'), ('General', 'General / Public')], default='General', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
